name: CI

on: [push, pull_request]
#on:
#  push:
#    branches: [ master-1.12 ]
#  pull_request:
#    # The branches below must be a subset of the branches above
#    branches: [ master-1.12 ]
#      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: chmod a+x gradlew
      - run: ./gradlew --version --no-daemon
      - run: ./gradlew setupCIWorkspace
      - run: ./gradlew clean build -x test
